<?php

/**
* Implementation of hook_feeds_plugins().
*/
function mailfeed_feeds_plugins() {
  $info = array();
  $info['MailFeedsImporter'] = array(
    'name' => 'Mailfeeds Importer',
    'description' => 'Importer for mailfeeds.',
    'handler' => array(
      'parent' => 'FeedsImporter', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class' => 'MailFeedsImporter',
      'file' => 'MailFeedsImporter.inc',
      'path' => drupal_get_path('module', 'mailfeeds') . '/classes',
    ),
  );
  $info['MailFeedsFetcher'] = array(
    'name' => 'Mailfeeds Fetcher',
    'description' => 'Fetcher for mailfeeds.',
    'handler' => array(
      'parent' => 'FeedsFetcher', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class' => 'MailFeedsFetcher',
      'file' => 'MailFeedsFetcher.inc',
      'path' => drupal_get_path('module', 'mailfeeds') . '/classes',
    ),
  );
  return $info;
}
