<?php

/**
* Implementation of hook_feeds_plugins().
*/
function mailfeeds_feeds_plugins() {
  $info = array();
  $info['MailFeedsParser'] = array(
    'name' => 'Mailfeeds Parser',
    'description' => 'Parser for mailfeeds.',
    'handler' => array(
      'parent' => 'FeedsParser', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class' => 'MailFeedsParser',
      'file' => 'MailFeedsParser.inc',
      'path' => drupal_get_path('module', 'mailfeeds') . '/classes',
    ),
  );
  $info['MailFeedsFetcher'] = array(
    'name' => 'Mailfeeds Fetcher',
    'description' => 'Fetcher for mailfeeds.',
    'handler' => array(
      'parent' => 'FeedsFetcher', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class' => 'MailFeedsFetcher',
      'file' => 'MailFeedsFetcher.inc',
      'path' => drupal_get_path('module', 'mailfeeds') . '/classes',
    ),
  );
  return $info;
}
